dist: xenial
language: node_js
node_js:
- 11
- 10
- 8
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y oathtool
jobs:
  include:
  - stage: publish code coverage
    node_js: '8'
    script:
    - npm run test:unit:ci-report-coverage
  - stage: release docs
    if: type != pull_request AND branch = master
    node_js: '8'
    script:
    - npm run generate-docs
    - npm run travis-deploy-github-pages
  - stage: npm release
    if: tag IS present
    node_js: '8'
    script:
    - scripts/publish.sh
env:
  global:
  - secure: J7wErb722xi1cdsVYAnuwrD1EjUhyLDNqtkF0R4xKVpjmGOXnFR444pDQrE8FoNj8AevvVXN7i5FTNDzOKIW1c+wXIpvzT1sPgTwDwl5Di6jr2WzjQtX4zWxA1CBojwu30P1mjErDd6Rvb9I9997zZY1KJ9mWnQ3GZxafkwNqyY19ctLWoSUjZnalVdBhxZC0f1iW8eWdpDe5qHIUSE2ecumPezKJSpcXsqR+glXQMYfq9PjRtG1lOB8G7I9grErzB/ya4fA2xyZU+Dm3anMqlz6eKI5xwOlfrxl+HVzPgq+slyjJt0LiJbljlCyaqSGU6gFv8DL10G5rYXfX5xms0UVvKfiCIuvnlxHTMD0vV9JjwYM9m7jNwiVDlbd2lpBypxvJ6Fb9KCfaBBJ/I8ihNfzas+9Tge74JrmQ4JZVvk0HqP1VxzZLjL4Z+NY/FXBZznuNowXzeEhWVW6ynYqU8OZCMmBPAPpmSdsHmjb3FwEE9NHprMh4P175ZegI3pP0REqE1whGvd1XnshxQYatmon2VMwb/Q9msXgl6kKAzXPSgse5+cOprAqcq5fW2aVjvW8jcgos0t74NeUuSJzv0AmNhUyTRdoxjhIEC5XmyEHu0UvGnrXy66S0uXLgge0Yyla7cZFxo1I26jCiMTIfDj5nHIJFyXT4hBEQ3k555Q=
  - secure: sr+L1a/8cWJVIpXfIhhRMBlHmU2zpfg4xH2Sz/JakgWuqwWI7NOkcNFHjn40VtaxOs6UgbQvMpvJooms2+wEwhuOFxSqoHYeb2as24XdNJUojeaVVUc7hNCwK31gqbnN0L8NBnUHHzlZ4y018sNQzKobpe7qb4Gtp48rC3Xsv8GQzXw+Ao5C9DnUZ+mFqN3zkrJqCK4Gkje72rM+DmeYiwiAGfDTtzMfPznJjjkYz9P92v/RYS9TuVzKr4R5yPb9gP6zLN7vbQyAeGolRk2vvo4V/fg9Wx5JNAMGnyemyU7whQyd07Q0cnYabSEwwdz9Du1vZFJKHwC0pRsxl2ua78afrarV/VMDO0oOFgSz73+crA3xi/ElJ0rVJJXb5gjp6wtQ69FFHhiudlR2posc3j8WdNoQVTAaDl/f04kWiilJ+OaeieUMNr0CmqliWXH4Ext8WlKeuzrbO3STw3qgyz636LE65rfc5cn/1NS2sa3vE56ApPR2uALP6yb688sSpOq+yJTv/Fpq2OqNvtiVMMSoZwV6+Nx47xaqM79SGkCHg9K95FUwATNxc9JBhyvPDu0VSwMQvO9EaGnwkndEGJJTPsPsq6v5gfTkBAhHINwTt3Z7J762KHqTsKd/HHxtAMJkRvPimy0YGvfYyckUj7ds4zkx1pBTDd3AYXaapoM=
  - secure: rfCkzM3iR+NNZ9v2lUiYHvSU6A2kS2n+6t0oT2gNEwUAgPjtJwyP4QeFNLnRHhZMIzp78OUSU8tUozVG7cnOq34NkL9J4TTACy/QozqlBbI3W/qcM50AyPU7EaQ5B+z7YLPREa4Kejl3/h5NTIHkgdHO8rEEHJpt3lwRQX+SLsvXva+nZFDDogVOZsR6qvllKtCW49WaRVtgtSd+EQPx06y3NMafvYHWLurOeTmR/n4QwZ1qiwjXy+MoQ7dar/jnI28D9i0eaUB8GQiuOd003n/iCkSbySikFIrnbAlpB1lgYL9udTk/npWYBUKzloRWQrMjOs+BknyZWayzAXN7JUV1QY3S1hX1qovjz48qjahKq2Zzz1d+pjpsG6neWBjTZnVGkbtp0O6CtStxrDMctSJH+gQi9mI0rE6NLkHBp4xhz+WT56YGxk6uPvosY4zzatFAUM2qY9q1ZkUstSmLDDUWCtvp5xq7RH+VaFfppxhTIE5DxfGUqxUB3CVohHltZ8DLCdMtkmQaxdxIgbtHMnR5ssKf33v0XK7EC5CzxfuiF5peJp5Iw9T7VyF9sqXRlanVk+iuq7C6cqS4EvuX689hRTmAgcst5susxST3r04uroM/HKWoQlSianAQAf5tQpPP0h4dR2/zSAq7huqZBVBLpUbNOIAT4hTzruL6uqs=
  - secure: bMHcFpDtYYZr7a7TOdszXTDyHC0LIhv+tGhCjg0ZMOR4HldYVbRgzhx9z/EjMTlvk8Jd0e8ogNH4WdMTM6q33qtC6T+Un3tFPcXDwOCr0xxlsdBGBVoXH3gTrMSEJbFkDTEn4nDookv8nliinKJkeZVGKjWVpIgybkEG2TKIIBfGaBQB9SfYCu49LtcpXUpS4ZniO5uUJ5ydrH7QjQ6mk9i0ZJL2vxSVHPHnSYdyudc2IPNt0QI73uUt8pbAD4T+5nsJYZw4IgmU+l9yrtIQbaHmS7JfzYJAJh9DZLKyZiH8iDbM4Cuq7OKQNwX4vF5OnUV7ywJ1qMAP6ELVWZjOQASVpJeIvjZQh25AMSJwnMO5D7gE/Q4xWvkTavHMHATRJsomI7CoEIl2GvYgij5L1sA5f6TAO52NswzsDUiql7zEy2iIXAyV2QITlSt+U5ua2Q5fFbDTMXG4YAkEVQ5yuZodnZg93B+XLJOBFReKKMNAdkas/vKRHYYH/X+vpPsUSeBxKIQgZybz/i7L0GedRdcFyV/3/ONAizHZtBoAYrY/n3AuO9iTz9ne2k69tv0r8EGyHGSNDH1Pjlg+ureg31pW1Es+2B4w40TMcLzWCWpiq8tqY3hQoTCbNhy76Mq9oJblCWI6hjHhUKdc+HcqZSjmR4aZ9TJfNiomBn9ByUI=
