dist: xenial
language: node_js
node_js:
- 11
- 10
- 8
jobs:
  include:
  - stage: publish code coverage
    node_js: '8'
    script:
    - npm run test:unit:ci-report-coverage
  - stage: release docs
    if: type != pull_request AND branch = master
    node_js: '8'
    script:
    - npm run generate-docs
    - npm run travis-deploy-github-pages
  - stage: npm release
    if: tag IS present
    node_js: '8'
    deploy:
      provider: npm
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      skip_cleanup: true
      on:
        tags: true
        repo: Nike-Inc/cerberus-node-client
env:
  global:
  - secure: HI1lYPsgqBUzjvWpiZ+B63ZOcKlGttRN0qA7mDXIfwuF+6QU+typao77G7N/9NAUjotUdIvIpVTq2Jv1NmHls3nc8NMIb3W7rOG0G/2IYNfYUnr9UaDFVgZ9zIr9dfXifJvBFRnOZJeXBkUj6kwER8it+jWzKwSJeuKDgSJkCJKtRUPBmerQEkSScOr2Wn2g/J43nWgI+/wChvS/Nq5RWytRA3apfhUbPd7reQITcV4eypBeOpL6aZ0qwC0u69VIcZXGELD7WMYagFqg/bJHoOb8sdlBXUQBGlEtE/fSgdvaZjg95fNYAbMSxt/fnWQNNyncSCwzepKHe9EnYTH4oNkKMiHwz8ULiqUovy/JE2io7cS20f4ZgfEW7DUIK4vd0pQqNepggRmmsQKzng3nMO+MQperrWaxcXKW0l5VxeAPZ1xRyDJA0jCFY0Q/EI2LONS5ItQU71gPjedHLYfC9FK2C8mtlSGagOM8WKTSXLpTGgmdqMK2OsI4bEYQUqUqX+FxHLmG21UZds8ia20QdS4CDHj7TnqST/X4ddZNvP0UMj3u0WxhvyaqeXc4SEGX34+LDSldM/imD7vVO8iS/3jnU2NtXXoTKIVoAcsKLGC7qNOHnNILCw5AnQeI9v4AM0Qppfq7/qNkchL6c6TTT8L9HoTHgz7IAsbvCXp+pEA=
  - secure: pat3i7ThKjvMMwlFA+OJw/N5cEuVtxGiGCsUF6DEetqzXTylz0RTWbCkMq0pG5DEriqDFWMVcl5PB3b8nFztpUq9fSv+HRJa/rM8wLTS9qAB044iHJ3O+5lyLid1XmnFSIT+jSO7Tadd5l3PVkZajnCQ64WNf1i8OfIBNQbzchREn2+OfGueLBAL1gXAgN1Lb/MWXOQrtq790lRZuOLZ/W7NBd33dAV2qaPErmjiAE26EArVAxY6/yszDHXtl9/JN6yM4qZtl3KqaGhkDt2iNkXcC8FwgsnhDJ1e0qwQixZRiWURpOE1vTV8tB+K4TCWDybkB9V9MOr+OvCExqjbVrEVgvKy4pukYx/2ORi++4CUPWqOvrYdNi2C4oHiqwyoLNuObAyUg/FzNQDfl3q8FTd7qh2yEAi+HftJLl1Agg4u91MTfTzt2KFEpEHVwkMPMS/ZN3nK6LVz94iqBP/+DsuaKkvC8xCpGfXPe5nQYIBctL7Ntdvh3l+ZIeN1hggRs0IbLJUh8vnftnmIE9+zLnRRHDB4zG42IyW29cnJ/WfCkXINb+EtoF0WwMKu5/aGtotO4m1T5RzWBfbJktdBDWxbuFq1jRQBbtICYn9gUlt4w1kY4GsfPTMOiSORmlZxOajcNvUHqGC85Vnbub73L5LoT8NCTnAMNzHBip4POfQ=
  - secure: J4nKEfQtUMHq4FzTUWxmKFbYUiVb65EXk8FgcdpNH62nbaGZ450K/jIciFwIiE4PcWhk51tExK0rUHxY0rUUpmG4pj3JT6XZCYzVPV/NnTZGnFbhUeLOFSTT0vBLge+qP7wRXel5/cgWhfsc6wdtkiKpwArST/yzZxvVFDsrezQJa+5sKFOJJ+wiOV+1CDWAd1r15n4PzioIKVY+aeDfkUYTB3qZjjG2B4OaQgHiY2h1InbFtMVzrSoMPEyrNFsP+pHLZ8DHbNyCMeKH5FfzYVAvTMjrSe5H+u1HcQ4PrN1oFZKgQlf0b1sr+ah1UYFB4FGVv57CFS13Vq1yo9sydqTRfWu+jS0qtVWgdHJVgo0mS83id6grxYcuw4xMaB/X9dc6wxf+gwsIGu2tmW92iRdxnpy5yI+HCfPDQ374dd4uRkpjuZ9pwhmKFpcwWXS7k9TAF8WcFcfG7hv70b+i2gRHpZQONg4BhyVv5RTqTPpyvE4HLlc5F1nA1HRauru74TwlnbRza4BG/tboMmr4UH6C9bf9UyBgkRbZdNF9Vv2IYpfStWqhx/5m/+3yqwedO6J7fFhJ/t4glQC41tiY+flf040SQHQ9v7TUzqf887Y2Gw1wmgapWtmf84jCP/uDjIl28XcsYH8v0c5Ony9JqhV/Fv5FK8v8oi4waRGpnHc=
