dist: xenial
language: node_js
node_js:
- 11
- 10
- 8
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y oathtool
jobs:
  include:
  - stage: publish code coverage
    node_js: '8'
    script:
    - npm run test:unit:ci-report-coverage
  - stage: release docs
    if: type != pull_request AND branch = master
    node_js: '8'
    script:
    - npm run generate-docs
    - npm run travis-deploy-github-pages
  - stage: npm release
    if: tag IS present
    node_js: '8'
    script:
    - scripts/publish.sh
env:
  global:
  - secure: J7wErb722xi1cdsVYAnuwrD1EjUhyLDNqtkF0R4xKVpjmGOXnFR444pDQrE8FoNj8AevvVXN7i5FTNDzOKIW1c+wXIpvzT1sPgTwDwl5Di6jr2WzjQtX4zWxA1CBojwu30P1mjErDd6Rvb9I9997zZY1KJ9mWnQ3GZxafkwNqyY19ctLWoSUjZnalVdBhxZC0f1iW8eWdpDe5qHIUSE2ecumPezKJSpcXsqR+glXQMYfq9PjRtG1lOB8G7I9grErzB/ya4fA2xyZU+Dm3anMqlz6eKI5xwOlfrxl+HVzPgq+slyjJt0LiJbljlCyaqSGU6gFv8DL10G5rYXfX5xms0UVvKfiCIuvnlxHTMD0vV9JjwYM9m7jNwiVDlbd2lpBypxvJ6Fb9KCfaBBJ/I8ihNfzas+9Tge74JrmQ4JZVvk0HqP1VxzZLjL4Z+NY/FXBZznuNowXzeEhWVW6ynYqU8OZCMmBPAPpmSdsHmjb3FwEE9NHprMh4P175ZegI3pP0REqE1whGvd1XnshxQYatmon2VMwb/Q9msXgl6kKAzXPSgse5+cOprAqcq5fW2aVjvW8jcgos0t74NeUuSJzv0AmNhUyTRdoxjhIEC5XmyEHu0UvGnrXy66S0uXLgge0Yyla7cZFxo1I26jCiMTIfDj5nHIJFyXT4hBEQ3k555Q=
  - secure: pat3i7ThKjvMMwlFA+OJw/N5cEuVtxGiGCsUF6DEetqzXTylz0RTWbCkMq0pG5DEriqDFWMVcl5PB3b8nFztpUq9fSv+HRJa/rM8wLTS9qAB044iHJ3O+5lyLid1XmnFSIT+jSO7Tadd5l3PVkZajnCQ64WNf1i8OfIBNQbzchREn2+OfGueLBAL1gXAgN1Lb/MWXOQrtq790lRZuOLZ/W7NBd33dAV2qaPErmjiAE26EArVAxY6/yszDHXtl9/JN6yM4qZtl3KqaGhkDt2iNkXcC8FwgsnhDJ1e0qwQixZRiWURpOE1vTV8tB+K4TCWDybkB9V9MOr+OvCExqjbVrEVgvKy4pukYx/2ORi++4CUPWqOvrYdNi2C4oHiqwyoLNuObAyUg/FzNQDfl3q8FTd7qh2yEAi+HftJLl1Agg4u91MTfTzt2KFEpEHVwkMPMS/ZN3nK6LVz94iqBP/+DsuaKkvC8xCpGfXPe5nQYIBctL7Ntdvh3l+ZIeN1hggRs0IbLJUh8vnftnmIE9+zLnRRHDB4zG42IyW29cnJ/WfCkXINb+EtoF0WwMKu5/aGtotO4m1T5RzWBfbJktdBDWxbuFq1jRQBbtICYn9gUlt4w1kY4GsfPTMOiSORmlZxOajcNvUHqGC85Vnbub73L5LoT8NCTnAMNzHBip4POfQ=
  - secure: J4nKEfQtUMHq4FzTUWxmKFbYUiVb65EXk8FgcdpNH62nbaGZ450K/jIciFwIiE4PcWhk51tExK0rUHxY0rUUpmG4pj3JT6XZCYzVPV/NnTZGnFbhUeLOFSTT0vBLge+qP7wRXel5/cgWhfsc6wdtkiKpwArST/yzZxvVFDsrezQJa+5sKFOJJ+wiOV+1CDWAd1r15n4PzioIKVY+aeDfkUYTB3qZjjG2B4OaQgHiY2h1InbFtMVzrSoMPEyrNFsP+pHLZ8DHbNyCMeKH5FfzYVAvTMjrSe5H+u1HcQ4PrN1oFZKgQlf0b1sr+ah1UYFB4FGVv57CFS13Vq1yo9sydqTRfWu+jS0qtVWgdHJVgo0mS83id6grxYcuw4xMaB/X9dc6wxf+gwsIGu2tmW92iRdxnpy5yI+HCfPDQ374dd4uRkpjuZ9pwhmKFpcwWXS7k9TAF8WcFcfG7hv70b+i2gRHpZQONg4BhyVv5RTqTPpyvE4HLlc5F1nA1HRauru74TwlnbRza4BG/tboMmr4UH6C9bf9UyBgkRbZdNF9Vv2IYpfStWqhx/5m/+3yqwedO6J7fFhJ/t4glQC41tiY+flf040SQHQ9v7TUzqf887Y2Gw1wmgapWtmf84jCP/uDjIl28XcsYH8v0c5Ony9JqhV/Fv5FK8v8oi4waRGpnHc=
  - secure: EO6pqnpvKaa6pCOSbVkHzhukhDp8aB+NYDs9GAlIqz2rfhVT4gQvC46AuNefKkbp66GIV8paWjub6Zksw/9c8kiCAvblC6HkW5eASXzhEUS8MrqiCbXMlZkVzH7hJGZRhXz2JdeE1cVzEJMvsugJgXdzwpIxHPhtBdR9yuLe6Lp+IcNITzh9t9MGk60xMe86URrmUWlrTH/zXab2A9TgdatgJPcTmF/pHM0D/qIZaCPFZtXmlUjtXS4i9io/rusWavmYo5lnXrzUU7y0psYoC/p89/Tjtosnv7eKjSS0iCBmzJDpo3LfVEG1iaLliydBKwxCcbhzbxQDAPP52Q/dXE5nu+sz161P6RRpZUt3//rmVQWu/TAJHusUdF4x4Gr0lmcTuHHF+HLH76j3p/5rngAZbwKyicOWK292Z3mww5kZzS7zXWJ37OMOZsq5s2Hml6BYqbexOSjU2KjLrRNuBsWLLUDn3oUPDdruawRcOPxk4BKzk8w7uWSBchRi892gawmDi93tuUJco+/SIONbUscGbWMtEnGygRXMFwalgIW1ZHv01Aoc2MFnNkPhmFse9IOLmcLkZie7y36JCoKi+53D9fh5O6POqRHTynm+qJ9XOI9vDQImb860g7etjRQQIkd1gxSrF2xEjB8VFKSHDs7qjKXcpRpsFwh8yv9PeT0=
