# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test:unit:local
      - name: Upload coverage report to CodeCov
        if: ${{ matrix.node-version == '10.x' }}
        uses: codecov/codecov-action@v1
        with:
          file: coverage/clover.xml # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true
      - name: Build Documentation
        if: ${{ github.ref == 'refs/heads/master' && matrix.node-version == '10.x' }}
        run: npm run generate-docs
      - name: Deploy 🚀
        if: ${{ github.ref == 'refs/heads/master' && matrix.node-version == '10.x' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/docs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
      - name: Slack notification when build fails
        if: ${{ failure() && github.ref == 'refs/heads/master'}}
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: cerberus-alerts
          SLACK_MESSAGE: 'Cerberus release workflow has failed :build-failed:'
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: Cerberus Build Failure Notification
          SLACK_USERNAME: GitHub Actions