# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Release
on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
        sudo apt-get -qq update
        sudo apt-get install -y oathtool
        npm install
        npm run test:unit:local
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: coverage/clover.xml # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true
      - name: Publish if version has been updated
          uses: pascalgn/npm-publish-action@1.3.4
          with: # All of theses inputs are optional
            tag_name: "v%s"
            tag_message: "v%s"
            commit_pattern: "^Release (\\S+)"
            workspace: "."
            publish_command: "npm"
            publish_args: "--otp=$(oathtool -b --totp ${{secrets.NPM_OTP}})"
          env: # More info about the environment variables in the README
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
            NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings
      - name: Slack notification when build fails
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: cerberus-alerts
          SLACK_MESSAGE: 'Cerberus release workflow has failed :build-failed:'
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: Cerberus Build Failure Notification
          SLACK_USERNAME: GitHub Actions